{% set name = "danish" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/danish-{{ version }}.tar.gz
  sha256: b11af697afa84d25e7236ac9d90283e8615ff90d83f85673322e9ac01e192f28

build:
  skip: true  # [py<38 or win]
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]
  skip: true  # [py==38]
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pybind11 >2.10
    - pip
    - setuptools
  run:
    - python
    - numpy
    - pyyaml
    - galsim
    - batoid
    - scipy

test:
  imports:
    - danish
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/jmeyers314/danish
  summary: Geometric donut engine
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
    - jmeyers314
