{% set name = "danish" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/danish-{{ version }}.tar.gz
  sha256: 209fd76a50bbac4cbaff1716ef1cd10a1532456ecbfcb26ec40df1acac1e0e1d

build:
  skip: true  # [py<38 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pybind11 >2.10
    - pip
  run:
    - python
    - numpy
    - pyyaml
    - galsim
    - batoid
    - scipy

test:
  imports:
    - danish
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jmeyers314/danish
  summary: Geometric donut engine
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
