{% set name = "danish" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/danish-{{ version }}.tar.gz
  sha256: fb42cf41c6fb8329cad2c0713e9cf929de04a56bce87defdbd9ce54f16035b10

build:
  skip: true  # [py<39 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=42
    - setuptools-scm
    - wheel
    - pybind11 >2.10
    - pip
  run:
    - python
    - numpy
    - pyyaml
    - galsim
    - batoid
    - scipy

test:
  imports:
    - danish
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/jmeyers314/danish
  summary: Geometric donut engine
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
    - jmeyers314
