{% set name = "danish" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/danish-{{ version }}.tar.gz
  sha256: 759180b1b5cf060284065fbb1776adfa00677c3cca3f7373c42578ad63f40dc8

build:
  skip: true  # [py<38 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pybind11 >2.10
    - pip
  run:
    - python
    - numpy
    - pyyaml
    - galsim
    - batoid
    - scipy

test:
  imports:
    - danish
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jmeyers314/danish
  summary: Geometric donut engine
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
